### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by GedeonGrays** [Miradae/Recurrent-Complex-Unofficial#1]
_Hello o/_

I noticed a question raised by a user of the Chunk-Pregenerator mod, and the mod's author, Speiger, mentioned in one of his [response comments](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator?comment=1196) that Minecraft has a memory leak that is related to the generation of structures. He also mentioned a similar problem in Recurrent Complex (I'm not very good at English, so I could be wrong, but vigilance will not be superfluous).

In general, I suggest just checking for a memory leak in the mod and fixing it if there is one.

_P.S. If there is no leak and I misunderstood Speiger's comment, I apologize in advance for your time. You can immediately close this Issue._

**Comment by Miradae** [comment]
Thx for the tip, I've checked the code but I couldn't find any leaks which the mod itself is the source of. Fixing minecraft leaks itself is not in the scope for this project for now. If anyone else notices any leaks while using this mod i'll do another deeper analysis.
